import io.vertx.core.Vertx;
import io.vertx.core.http.HttpMethod;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Main {
	
	public static void main (String[] args) {
		Main.class.getClassLoader().getResource("index.html");
		Vertx.vertx()
			.createHttpServer()
			.requestHandler(requestHandler -> {
				// Get request method
				HttpMethod method = requestHandler.method();
				// Return form html
				if(method.equals(HttpMethod.GET)) {
					requestHandler.response().sendFile("index.html").toString();
				} else if (method.equals(HttpMethod.POST)) {
					requestHandler.response().setChunked(true);
					requestHandler.setExpectMultipart(true);
					requestHandler.endHandler((v) -> {
						requestHandler.response().write("{\n");
						for (String attr : requestHandler.formAttributes().names()) {
							requestHandler.response()
								.write("\"" + attr + "\" : \" +" + requestHandler.formAttributes().get(attr) + "\"\n");
						}
						requestHandler.response().write("}");
						requestHandler.response().end();
			        });
				} else {
					requestHandler.response().setStatusCode(400).end();
				}
			})
			.listen(80);
	}
}
